import type { ConfigDeDestino } from './tipos.ts';

/**
 * O Mexico tem TRES fusos: Quintana Roo em UTC-5, o centro em UTC-6 e a
 * Baja California Sur em UTC-7 (o pais acabou com o horario de verao em
 * 2022). O destino declara o do centro, e as cidades fora dele sobrescrevem
 * pelo mapa abaixo.
 */
export const FUSO_POR_CIDADE: Record<string, number> = {
  cancun: -300,
  'playa-del-carmen': -300,
  tulum: -300,
  bacalar: -300,
  'isla-mujeres': -300,
  cozumel: -300,
  'la-paz': -420,
  'todos-santos': -420,
  'los-cabos': -420,
  loreto: -420,
};

export const mexico: ConfigDeDestino = {
  id: 'mexico',
  nome: 'Mexico',
  paisNome: 'Mexico',
  cobertura:
    'Cobre 26 bases do centro, do Caribe, da peninsula de Yucatan, de Oaxaca, de Chiapas, da Baja Sur e do Pacifico. Fora do pacote: todo o norte (Chihuahua, Nuevo Leon, Sonora), Veracruz e Michoacan.',
  codigoPais: 'MX',
  moeda: 'MXN',
  fuso: 'America/Mexico_City',
  fusoOffsetMinutos: -360,
  idiomas: ['es'],
  // Do extremo sul de Chiapas ao norte da Baja; a leste alcanca Isla
  // Mujeres (-86,73) e a oeste a Ilha Guadalupe.
  caixaDelimitadora: { latMin: 14.3, latMax: 32.8, lngMin: -118.5, lngMax: -86.4 },
  pastaDePesquisa: 'pesquisa/mexico',
  fusoPorCidade: FUSO_POR_CIDADE,

  regiaoDaCidade: {
    'cidade-do-mexico': 'valle-do-mexico',
    puebla: 'valle-do-mexico',
    cancun: 'caribe-mexicano',
    'playa-del-carmen': 'caribe-mexicano',
    tulum: 'caribe-mexicano',
    bacalar: 'caribe-mexicano',
    'isla-mujeres': 'caribe-mexicano',
    cozumel: 'caribe-mexicano',
    merida: 'yucatan',
    valladolid: 'yucatan',
    oaxaca: 'oaxaca-vale',
    'puerto-escondido': 'oaxaca-costa',
    mazunte: 'oaxaca-costa',
    huatulco: 'oaxaca-costa',
    'san-cristobal': 'chiapas',
    palenque: 'chiapas',
    'la-paz': 'baja-california-sur',
    'todos-santos': 'baja-california-sur',
    'los-cabos': 'baja-california-sur',
    loreto: 'baja-california-sur',
    'puerto-vallarta': 'pacifico-central',
    sayulita: 'pacifico-central',
    guanajuato: 'bajio',
    'san-miguel-de-allende': 'bajio',
    queretaro: 'bajio',
    guadalajara: 'bajio',
  },

  nomeDaCidade: {
    'cidade-do-mexico': 'Cidade do Mexico',
    puebla: 'Puebla',
    cancun: 'Cancun',
    'playa-del-carmen': 'Playa del Carmen',
    tulum: 'Tulum',
    bacalar: 'Bacalar',
    'isla-mujeres': 'Isla Mujeres',
    cozumel: 'Cozumel',
    merida: 'Merida',
    valladolid: 'Valladolid',
    oaxaca: 'Oaxaca de Juarez',
    'puerto-escondido': 'Puerto Escondido',
    mazunte: 'Mazunte',
    huatulco: 'Huatulco',
    'san-cristobal': 'San Cristobal de las Casas',
    palenque: 'Palenque',
    'la-paz': 'La Paz',
    'todos-santos': 'Todos Santos',
    'los-cabos': 'Los Cabos',
    loreto: 'Loreto',
    'puerto-vallarta': 'Puerto Vallarta',
    sayulita: 'Sayulita',
    guanajuato: 'Guanajuato',
    'san-miguel-de-allende': 'San Miguel de Allende',
    queretaro: 'Queretaro',
    guadalajara: 'Guadalajara',
  },

  /**
   * Nome de exibicao da zona turistica. Sem isto o conversor capitaliza o
   * id, e "bahia-dende" virava "Bahia Dende" - que nao e o nome de nada.
   */
  nomeDaZona: {
    'valle-do-mexico': 'Vale do Mexico',
    'caribe-mexicano': 'Riviera Maya e Caribe',
    yucatan: 'Peninsula de Yucatan',
    'oaxaca-vale': 'Vales Centrais de Oaxaca',
    'oaxaca-costa': 'Costa de Oaxaca',
    chiapas: 'Chiapas',
    'baja-california-sur': 'Baja California Sur',
    'pacifico-central': 'Pacifico central',
    bajio: 'Bajio',
  },

  descricaoDaRegiao: {
    'valle-do-mexico': 'Planalto central: Cidade do Mexico, Teotihuacan, Puebla e Cholula.',
    'caribe-mexicano': 'Quintana Roo: Cancun, Playa del Carmen, Tulum, Bacalar e as ilhas.',
    yucatan: 'Interior do Yucatan: Merida, Valladolid, Chichen Itza, Uxmal e os cenotes.',
    'oaxaca-vale': 'Vale de Oaxaca: a cidade, Monte Alban, Mitla, Hierve el Agua e o mezcal.',
    'oaxaca-costa': 'Costa de Oaxaca: Puerto Escondido, Mazunte, Zipolite e Huatulco.',
    chiapas: 'Chiapas: San Cristobal, Palenque, Canon del Sumidero e as cachoeiras.',
    'baja-california-sur': 'Baja California Sur: La Paz, Espiritu Santo, Todos Santos e Los Cabos.',
    'pacifico-central': 'Pacifico central: Puerto Vallarta, Sayulita e as Islas Marietas.',
    bajio: 'Bajio e Jalisco: Guanajuato, San Miguel de Allende, Queretaro, Guadalajara e Tequila.',
  },

  cidadeDoItem: {
    // Vale do Mexico
    'cidade-do-mexico': 'cidade-do-mexico',
    teotihuacan: 'cidade-do-mexico',
    xochimilco: 'cidade-do-mexico',
    puebla: 'puebla',
    // Caribe
    cancun: 'cancun',
    'playa-del-carmen': 'playa-del-carmen',
    tulum: 'tulum',
    bacalar: 'bacalar',
    'isla-mujeres': 'isla-mujeres',
    cozumel: 'cozumel',
    // Yucatan
    merida: 'merida',
    valladolid: 'valladolid',
    'chichen-itza': 'valladolid',
    uxmal: 'merida',
    izamal: 'merida',
    celestun: 'merida',
    'rio-lagartos': 'valladolid',
    progreso: 'merida',
    // Oaxaca
    oaxaca: 'oaxaca',
    'monte-alban': 'oaxaca',
    'hierve-el-agua': 'oaxaca',
    mitla: 'oaxaca',
    'puerto-escondido': 'puerto-escondido',
    mazunte: 'mazunte',
    zipolite: 'mazunte',
    huatulco: 'huatulco',
    // Chiapas
    'san-cristobal': 'san-cristobal',
    palenque: 'palenque',
    tuxtla: 'san-cristobal',
    'agua-azul': 'palenque',
    montebello: 'san-cristobal',
    chiflon: 'san-cristobal',
    // Baja e Pacifico
    'la-paz': 'la-paz',
    'todos-santos': 'todos-santos',
    'los-cabos': 'los-cabos',
    loreto: 'loreto',
    'puerto-vallarta': 'puerto-vallarta',
    sayulita: 'sayulita',
    // Bajio
    guanajuato: 'guanajuato',
    'san-miguel-de-allende': 'san-miguel-de-allende',
    queretaro: 'queretaro',
    'dolores-hidalgo': 'guanajuato',
    bernal: 'queretaro',
    guadalajara: 'guadalajara',
    tequila: 'guadalajara',
  },

  prefixoId: {
    'cidade-do-mexico': 'mex',
    puebla: 'pue',
    cancun: 'cun',
    'playa-del-carmen': 'pdc',
    tulum: 'tul',
    bacalar: 'bac',
    'isla-mujeres': 'imu',
    cozumel: 'czm',
    merida: 'mid',
    valladolid: 'vld',
    oaxaca: 'oax',
    'puerto-escondido': 'pxm',
    mazunte: 'maz',
    huatulco: 'hux',
    'san-cristobal': 'sct',
    palenque: 'plq',
    'la-paz': 'lap',
    'todos-santos': 'tds',
    'los-cabos': 'cab',
    loreto: 'lto',
    'puerto-vallarta': 'pvr',
    sayulita: 'say',
    guanajuato: 'gto',
    'san-miguel-de-allende': 'sma',
    queretaro: 'qro',
    guadalajara: 'gdl',
  },

  climaParaCidades: [
    { contem: /Vale do M[eé]xico/i, cidades: ['cidade-do-mexico'], regiao: 'valle-do-mexico' },
    { contem: /^Puebla/i, cidades: ['puebla'], regiao: 'valle-do-mexico' },
    {
      contem: /Caribe \/ Quintana Roo/i,
      cidades: ['cancun', 'playa-del-carmen', 'tulum', 'bacalar', 'isla-mujeres', 'cozumel'],
      regiao: 'caribe-mexicano',
    },
    { contem: /Yucat[aá]n interior/i, cidades: ['merida', 'valladolid'], regiao: 'yucatan' },
    { contem: /Oaxaca - serra/i, cidades: ['oaxaca'], regiao: 'oaxaca-vale' },
    {
      contem: /Oaxaca - costa/i,
      cidades: ['huatulco', 'puerto-escondido', 'mazunte'],
      regiao: 'oaxaca-costa',
    },
    { contem: /Chiapas - serra/i, cidades: ['san-cristobal'], regiao: 'chiapas' },
    // A depressao central (Tuxtla) nao serve para Palenque, que e selva
    // de baixada: Palenque fica sem clima no banco ate alguem pesquisar.
    { contem: /Chiapas - depress/i, cidades: [], regiao: 'chiapas' },
    { contem: /Baja California Sur - La Paz/i, cidades: ['la-paz'], regiao: 'baja-california-sur' },
    {
      contem: /Baja California Sur - Los Cabos/i,
      cidades: ['los-cabos', 'todos-santos'],
      regiao: 'baja-california-sur',
    },
    {
      contem: /Pac[ií]fico central/i,
      cidades: ['puerto-vallarta', 'sayulita'],
      regiao: 'pacifico-central',
    },
    { contem: /Jalisco - Guadalajara/i, cidades: ['guadalajara'], regiao: 'bajio' },
    { contem: /Baj[ií]o - Le[oó]n/i, cidades: ['guanajuato', 'queretaro'], regiao: 'bajio' },
    { contem: /Baj[ií]o alto/i, cidades: ['san-miguel-de-allende'], regiao: 'bajio' },
  ],

  // Ordem importa: o mais especifico primeiro.
  apelidosDeCidade: [
    [/san miguel de allende/i, 'san-miguel-de-allende'],
    [/san crist[oó]bal/i, 'san-cristobal'],
    [/cidade do m[eé]xico|ciudad de m[eé]xico|\bcdmx\b|teotihuac[aá]n|xochimilco/i, 'cidade-do-mexico'],
    [/puerto escondido/i, 'puerto-escondido'],
    [/puerto vallarta/i, 'puerto-vallarta'],
    [/todos santos/i, 'todos-santos'],
    [/los cabos|cabo san lucas|san jos[eé] del cabo/i, 'los-cabos'],
    [/\bla paz\b/i, 'la-paz'],
    [/playa del carmen/i, 'playa-del-carmen'],
    [/isla mujeres/i, 'isla-mujeres'],
    [/chich[eé]n itz[aá]|valladolid/i, 'valladolid'],
    [/m[eé]rida|uxmal|izamal|celest[uú]n|progreso/i, 'merida'],
    [/canc[uú]n/i, 'cancun'],
    [/tulum/i, 'tulum'],
    [/bacalar/i, 'bacalar'],
    [/cozumel/i, 'cozumel'],
    [/mazunte|zipolite/i, 'mazunte'],
    [/huatulco/i, 'huatulco'],
    [/oaxaca/i, 'oaxaca'],
    [/palenque|agua azul|misol/i, 'palenque'],
    [/guadalajara|tequila/i, 'guadalajara'],
    [/sayulita/i, 'sayulita'],
    [/guanajuato|dolores hidalgo/i, 'guanajuato'],
    [/quer[eé]taro|bernal/i, 'queretaro'],
    [/puebla|cholula/i, 'puebla'],
    [/loreto/i, 'loreto'],
  ],

  iataParaCidade: {
    MEX: 'cidade-do-mexico',
    NLU: 'cidade-do-mexico',
    CUN: 'cancun',
    CZM: 'cozumel',
    MID: 'merida',
    OAX: 'oaxaca',
    PXM: 'puerto-escondido',
    HUX: 'huatulco',
    TGZ: 'san-cristobal',
    SJD: 'los-cabos',
    LAP: 'la-paz',
    LTO: 'loreto',
    PVR: 'puerto-vallarta',
    BJX: 'guanajuato',
    QRO: 'queretaro',
    GDL: 'guadalajara',
  },

  fatores: {
    // Megalopole com transito pesado; o metro salva, mas tem baldeacao longa.
    'cidade-do-mexico': {
      'a-pe': { kmh: 4.5, fatorRota: 1.3 },
      'carro-app': { kmh: 16, fatorRota: 1.5 },
      'transporte-publico': { kmh: 15, fatorRota: 1.45 },
      'veiculo-alugado': { kmh: 16, fatorRota: 1.5 },
    },
    // Zona hoteleira e uma fita de 22 km: distancia grande, transito leve.
    cancun: {
      'a-pe': { kmh: 4.5, fatorRota: 1.2 },
      'carro-app': { kmh: 28, fatorRota: 1.2 },
      'transporte-publico': { kmh: 20, fatorRota: 1.25 },
      'veiculo-alugado': { kmh: 28, fatorRota: 1.2 },
    },
    // Centro de grelha caminhavel, resto de carro pela 307.
    'playa-del-carmen': {
      'a-pe': { kmh: 4.5, fatorRota: 1.15 },
      'carro-app': { kmh: 25, fatorRota: 1.25 },
      'transporte-publico': { kmh: 20, fatorRota: 1.3 },
      'veiculo-alugado': { kmh: 25, fatorRota: 1.25 },
    },
    // Centro colonial plano e compacto, em grelha.
    merida: {
      'a-pe': { kmh: 4.8, fatorRota: 1.15 },
      'carro-app': { kmh: 24, fatorRota: 1.25 },
      'transporte-publico': { kmh: 16, fatorRota: 1.4 },
      'veiculo-alugado': { kmh: 24, fatorRota: 1.25 },
    },
    // Centro andavel; o vale exige carro ou tour.
    oaxaca: {
      'a-pe': { kmh: 4.5, fatorRota: 1.25 },
      'carro-app': { kmh: 20, fatorRota: 1.35 },
      'transporte-publico': { kmh: 14, fatorRota: 1.45 },
      'veiculo-alugado': { kmh: 20, fatorRota: 1.35 },
    },
    // Ladeiras e tuneis: andar a pe rende menos que o normal.
    guanajuato: {
      'a-pe': { kmh: 3.8, fatorRota: 1.4 },
      'carro-app': { kmh: 18, fatorRota: 1.5 },
      'transporte-publico': { kmh: 14, fatorRota: 1.5 },
      'veiculo-alugado': { kmh: 18, fatorRota: 1.5 },
    },
  },
};
