/**
 * Nordeste brasileiro.
 *
 * Primeiro destino DOMESTICO do banco, e por isso ele testa o app de um
 * jeito que Colombia e Mexico nao testavam: mesma moeda da pessoa, sem
 * visto, sem voo internacional, e um fuso diferente dentro do proprio
 * destino (Fernando de Noronha e UTC-2, o resto UTC-3).
 *
 * Recorte: 23 bases nos 9 estados. Base e lugar onde se dorme; o que se
 * visita e volta no mesmo dia entra como item da base, via `cidadeDoItem`.
 */
import type { ConfigDeDestino } from './tipos.ts';

export const nordeste: ConfigDeDestino = {
  id: 'nordeste',
  nome: 'Nordeste brasileiro',
  codigoPais: 'BR',
  moeda: 'BRL',
  fuso: 'America/Sao_Paulo',
  fusoOffsetMinutos: -180,
  idiomas: ['pt'],
  // Do delta do Parnaiba (norte) a Trancoso (sul); a leste vai ate
  // Fernando de Noronha, que fica a 350 km da costa.
  caixaDelimitadora: { latMin: -19.0, latMax: -0.8, lngMin: -49.0, lngMax: -32.0 },

  pastaDePesquisa: 'pesquisa/nordeste',

  regiaoDaCidade: {
    'sao-luis': 'maranhao',
    barreirinhas: 'lencois-maranhenses',
    atins: 'lencois-maranhenses',
    parnaiba: 'piaui-litoral',
    'sao-raimundo-nonato': 'piaui-sertao',
    jericoacoara: 'ceara',
    fortaleza: 'ceara',
    'canoa-quebrada': 'ceara',
    natal: 'rio-grande-do-norte',
    pipa: 'rio-grande-do-norte',
    'joao-pessoa': 'paraiba',
    recife: 'pernambuco',
    'porto-de-galinhas': 'pernambuco',
    'fernando-de-noronha': 'fernando-de-noronha',
    maceio: 'alagoas',
    maragogi: 'alagoas',
    'sao-miguel-dos-milagres': 'alagoas',
    aracaju: 'sergipe',
    salvador: 'bahia-salvador',
    'morro-de-sao-paulo': 'bahia-dende',
    itacare: 'bahia-cacau',
    lencois: 'chapada-diamantina',
    trancoso: 'bahia-descobrimento',
  },

  nomeDaCidade: {
    'sao-luis': 'São Luís',
    barreirinhas: 'Barreirinhas',
    atins: 'Atins',
    parnaiba: 'Parnaíba',
    'sao-raimundo-nonato': 'São Raimundo Nonato',
    jericoacoara: 'Jericoacoara',
    fortaleza: 'Fortaleza',
    'canoa-quebrada': 'Canoa Quebrada',
    natal: 'Natal',
    pipa: 'Pipa',
    'joao-pessoa': 'João Pessoa',
    recife: 'Recife',
    'porto-de-galinhas': 'Porto de Galinhas',
    'fernando-de-noronha': 'Fernando de Noronha',
    maceio: 'Maceió',
    maragogi: 'Maragogi',
    'sao-miguel-dos-milagres': 'São Miguel dos Milagres',
    aracaju: 'Aracaju',
    salvador: 'Salvador',
    'morro-de-sao-paulo': 'Morro de São Paulo',
    itacare: 'Itacaré',
    lencois: 'Lençóis',
    trancoso: 'Trancoso',
  },

  descricaoDaRegiao: {
    maranhao: 'São Luís e Alcântara: azulejo português, reggae e o caminho para os Lençóis.',
    'lencois-maranhenses': 'Dunas e lagoas de água doce que só existem cheias entre junho e setembro.',
    'piaui-litoral': 'Delta do Parnaíba: o único delta em mar aberto das Américas.',
    'piaui-sertao': 'Serra da Capivara: arte rupestre com datação que discute o povoamento da América.',
    ceara: 'Dunas, vento constante e 570 km de litoral; Jericoacoara é o ímã.',
    'rio-grande-do-norte': 'Falésias, buggy e o mar mais quente da costa.',
    paraiba: 'João Pessoa e o ponto mais oriental das Américas.',
    pernambuco: 'Recife e Olinda de um lado, piscinas naturais do outro.',
    'fernando-de-noronha': 'Arquipélago com entrada limitada, taxa diária e o melhor mergulho do país.',
    alagoas: 'Mar verde e piscinas naturais; a Costa dos Corais tem 135 km de recife.',
    sergipe: 'Aracaju, os canyons do São Francisco e o menor estado do país.',
    'bahia-salvador': 'Salvador: Pelourinho, candomblé, e a base para a Baía de Todos-os-Santos.',
    'bahia-dende': 'Morro de São Paulo e Boipeba: ilha sem carro, chegada de catamarã.',
    'bahia-cacau': 'Itacaré e a Costa do Cacau: surfe, mata atlântica e cachoeira.',
    'chapada-diamantina': 'Serra, cachoeira e gruta no centro da Bahia; nada de praia.',
    'bahia-descobrimento': 'Trancoso, Arraial d’Ajuda e Caraíva: o sul da Bahia que ficou caro.',
  },

  /**
   * Como o pesquisador pode ter nomeado a cidade de um item -> base.
   * Bate-volta aponta para a base de onde se sai e volta no mesmo dia.
   */
  cidadeDoItem: {
    'sao-luis': 'sao-luis',
    alcantara: 'sao-luis',
    'raposa': 'sao-luis',
    barreirinhas: 'barreirinhas',
    'lencois-maranhenses': 'barreirinhas',
    'santo-amaro': 'barreirinhas',
    atins: 'atins',
    'cardosa': 'atins',
    parnaiba: 'parnaiba',
    'delta-do-parnaiba': 'parnaiba',
    'luis-correia': 'parnaiba',
    barra_grande: 'parnaiba',
    'barra-grande': 'parnaiba',
    'sao-raimundo-nonato': 'sao-raimundo-nonato',
    'serra-da-capivara': 'sao-raimundo-nonato',
    teresina: 'sao-raimundo-nonato',
    jericoacoara: 'jericoacoara',
    jeri: 'jericoacoara',
    'tatajuba': 'jericoacoara',
    prea: 'jericoacoara',
    guriu: 'jericoacoara',
    'lagoa-do-paraiso': 'jericoacoara',
    fortaleza: 'fortaleza',
    cumbuco: 'fortaleza',
    'beach-park': 'fortaleza',
    'aquiraz': 'fortaleza',
    'canoa-quebrada': 'canoa-quebrada',
    aracati: 'canoa-quebrada',
    majorlandia: 'canoa-quebrada',
    'morro-branco': 'canoa-quebrada',
    natal: 'natal',
    'genipabu': 'natal',
    'maracajau': 'natal',
    'sao-miguel-do-gostoso': 'natal',
    pirangi: 'natal',
    pipa: 'pipa',
    'tibau-do-sul': 'pipa',
    'joao-pessoa': 'joao-pessoa',
    'ponta-do-seixas': 'joao-pessoa',
    'praia-do-jacare': 'joao-pessoa',
    cabedelo: 'joao-pessoa',
    'areia': 'joao-pessoa',
    recife: 'recife',
    olinda: 'recife',
    'ilha-de-itamaraca': 'recife',
    'porto-de-galinhas': 'porto-de-galinhas',
    'ipojuca': 'porto-de-galinhas',
    'carneiros': 'porto-de-galinhas',
    'praia-dos-carneiros': 'porto-de-galinhas',
    'fernando-de-noronha': 'fernando-de-noronha',
    noronha: 'fernando-de-noronha',
    maceio: 'maceio',
    'praia-do-frances': 'maceio',
    'marechal-deodoro': 'maceio',
    maragogi: 'maragogi',
    'japaratinga': 'maragogi',
    'sao-miguel-dos-milagres': 'sao-miguel-dos-milagres',
    porto_de_pedras: 'sao-miguel-dos-milagres',
    'porto-de-pedras': 'sao-miguel-dos-milagres',
    aracaju: 'aracaju',
    'canyon-do-xingo': 'aracaju',
    'canindé-de-sao-francisco': 'aracaju',
    'sao-cristovao': 'aracaju',
    salvador: 'salvador',
    'itaparica': 'salvador',
    'praia-do-forte': 'salvador',
    'baia-de-todos-os-santos': 'salvador',
    'morro-de-sao-paulo': 'morro-de-sao-paulo',
    boipeba: 'morro-de-sao-paulo',
    'cairu': 'morro-de-sao-paulo',
    itacare: 'itacare',
    ilheus: 'itacare',
    'maraú': 'itacare',
    'barra-grande-marau': 'itacare',
    lencois: 'lencois',
    'chapada-diamantina': 'lencois',
    'vale-do-capao': 'lencois',
    'mucuge': 'lencois',
    'poco-encantado': 'lencois',
    trancoso: 'trancoso',
    'arraial-dajuda': 'trancoso',
    'porto-seguro': 'trancoso',
    caraiva: 'trancoso',
    'praia-do-espelho': 'trancoso',
  },

  prefixoId: {
    'sao-luis': 'slz',
    barreirinhas: 'brr',
    atins: 'atn',
    parnaiba: 'pnb',
    'sao-raimundo-nonato': 'srn',
    jericoacoara: 'jeri',
    fortaleza: 'for',
    'canoa-quebrada': 'cnq',
    natal: 'nat',
    pipa: 'pipa',
    'joao-pessoa': 'jpa',
    recife: 'rec',
    'porto-de-galinhas': 'pdg',
    'fernando-de-noronha': 'fen',
    maceio: 'mcz',
    maragogi: 'mrg',
    'sao-miguel-dos-milagres': 'smm',
    aracaju: 'aju',
    salvador: 'ssa',
    'morro-de-sao-paulo': 'msp',
    itacare: 'ita',
    lencois: 'lec',
    trancoso: 'trc',
  },

  climaParaCidades: [
    { contem: /maranh|s[ãa]o lu[íi]s/i, cidades: ['sao-luis'], regiao: 'maranhao' },
    {
      contem: /len[çc][óo]is maranhenses|barreirinhas|atins/i,
      cidades: ['barreirinhas', 'atins'],
      regiao: 'lencois-maranhenses',
    },
    { contem: /parna[íi]ba|delta/i, cidades: ['parnaiba'], regiao: 'piaui-litoral' },
    {
      contem: /capivara|s[ãa]o raimundo|sert[ãa]o do piau/i,
      cidades: ['sao-raimundo-nonato'],
      regiao: 'piaui-sertao',
    },
    {
      contem: /cear|fortaleza|jericoacoara|canoa quebrada/i,
      cidades: ['fortaleza', 'jericoacoara', 'canoa-quebrada'],
      regiao: 'ceara',
    },
    {
      contem: /rio grande do norte|natal|pipa/i,
      cidades: ['natal', 'pipa'],
      regiao: 'rio-grande-do-norte',
    },
    { contem: /para[íi]ba|jo[ãa]o pessoa/i, cidades: ['joao-pessoa'], regiao: 'paraiba' },
    {
      contem: /pernambuco|recife|olinda|porto de galinhas/i,
      cidades: ['recife', 'porto-de-galinhas'],
      regiao: 'pernambuco',
    },
    {
      contem: /noronha/i,
      cidades: ['fernando-de-noronha'],
      regiao: 'fernando-de-noronha',
    },
    {
      contem: /alagoas|macei[óo]|maragogi|milagres/i,
      cidades: ['maceio', 'maragogi', 'sao-miguel-dos-milagres'],
      regiao: 'alagoas',
    },
    { contem: /sergipe|aracaju/i, cidades: ['aracaju'], regiao: 'sergipe' },
    { contem: /salvador|rec[ôo]ncavo/i, cidades: ['salvador'], regiao: 'bahia-salvador' },
    {
      contem: /morro de s[ãa]o paulo|boipeba|tinhar[ée]/i,
      cidades: ['morro-de-sao-paulo'],
      regiao: 'bahia-dende',
    },
    { contem: /itacar[ée]|ilh[ée]us|costa do cacau/i, cidades: ['itacare'], regiao: 'bahia-cacau' },
    {
      contem: /chapada diamantina|len[çc][óo]is \(bahia\)/i,
      cidades: ['lencois'],
      regiao: 'chapada-diamantina',
    },
    {
      contem: /trancoso|arraial|porto seguro|cara[íi]va/i,
      cidades: ['trancoso'],
      regiao: 'bahia-descobrimento',
    },
  ],

  apelidosDeCidade: [
    [/s[ãa]o lu[íi]s/i, 'sao-luis'],
    [/barreirinhas/i, 'barreirinhas'],
    [/atins/i, 'atins'],
    [/parna[íi]ba/i, 'parnaiba'],
    [/s[ãa]o raimundo nonato|capivara/i, 'sao-raimundo-nonato'],
    [/jericoacoara|\bjeri\b/i, 'jericoacoara'],
    [/fortaleza/i, 'fortaleza'],
    [/canoa quebrada|aracati/i, 'canoa-quebrada'],
    [/natal/i, 'natal'],
    [/\bpipa\b|tibau do sul/i, 'pipa'],
    [/jo[ãa]o pessoa/i, 'joao-pessoa'],
    [/recife|olinda/i, 'recife'],
    [/porto de galinhas|ipojuca/i, 'porto-de-galinhas'],
    [/noronha/i, 'fernando-de-noronha'],
    [/macei[óo]/i, 'maceio'],
    [/maragogi/i, 'maragogi'],
    [/s[ãa]o miguel dos milagres/i, 'sao-miguel-dos-milagres'],
    [/aracaju/i, 'aracaju'],
    [/salvador/i, 'salvador'],
    [/morro de s[ãa]o paulo|boipeba/i, 'morro-de-sao-paulo'],
    [/itacar[ée]|ilh[ée]us/i, 'itacare'],
    [/len[çc][óo]is\b(?! maranhenses)|chapada diamantina/i, 'lencois'],
    [/trancoso|arraial d|porto seguro|cara[íi]va/i, 'trancoso'],
  ],

  iataParaCidade: {
    SLZ: 'sao-luis',
    PHB: 'parnaiba',
    THE: 'sao-raimundo-nonato',
    JJD: 'jericoacoara',
    FOR: 'fortaleza',
    NAT: 'natal',
    JPA: 'joao-pessoa',
    REC: 'recife',
    FEN: 'fernando-de-noronha',
    MCZ: 'maceio',
    AJU: 'aracaju',
    SSA: 'salvador',
    IOS: 'itacare',
    LEC: 'lencois',
    BPS: 'trancoso',
  },

  /**
   * Fatores de deslocamento. Entrada do estimador, nao afirmacao sobre o
   * mundo: a camada 3 sempre aparece rotulada como estimativa.
   *
   * O que muda aqui em relacao a Colombia e Mexico: vilas de praia onde
   * ninguem anda de carro (Jericoacoara proibe carro de passeio na vila,
   * Morro de Sao Paulo e Atins nao tem rua asfaltada) e capitais extensas
   * e congestionadas (Salvador, Recife, Fortaleza).
   */
  fatores: {
    // Capital extensa, em vale e ladeira, transito pesado.
    salvador: {
      'a-pe': { kmh: 4.2, fatorRota: 1.4 },
      'carro-app': { kmh: 19, fatorRota: 1.5 },
      'transporte-publico': { kmh: 13, fatorRota: 1.6 },
      'veiculo-alugado': { kmh: 18, fatorRota: 1.5 },
    },
    recife: {
      'a-pe': { kmh: 4.5, fatorRota: 1.3 },
      'carro-app': { kmh: 20, fatorRota: 1.45 },
      'transporte-publico': { kmh: 14, fatorRota: 1.55 },
      'veiculo-alugado': { kmh: 19, fatorRota: 1.45 },
    },
    fortaleza: {
      'a-pe': { kmh: 4.6, fatorRota: 1.28 },
      'carro-app': { kmh: 23, fatorRota: 1.4 },
      'transporte-publico': { kmh: 15, fatorRota: 1.5 },
      'veiculo-alugado': { kmh: 22, fatorRota: 1.4 },
    },
    natal: {
      'a-pe': { kmh: 4.6, fatorRota: 1.3 },
      'carro-app': { kmh: 25, fatorRota: 1.4 },
      'transporte-publico': { kmh: 15, fatorRota: 1.5 },
      'veiculo-alugado': { kmh: 24, fatorRota: 1.4 },
    },
    maceio: {
      'a-pe': { kmh: 4.6, fatorRota: 1.28 },
      'carro-app': { kmh: 24, fatorRota: 1.4 },
      'transporte-publico': { kmh: 15, fatorRota: 1.5 },
      'veiculo-alugado': { kmh: 23, fatorRota: 1.4 },
    },
    'joao-pessoa': {
      'a-pe': { kmh: 4.7, fatorRota: 1.25 },
      'carro-app': { kmh: 26, fatorRota: 1.35 },
      'transporte-publico': { kmh: 16, fatorRota: 1.45 },
      'veiculo-alugado': { kmh: 25, fatorRota: 1.35 },
    },
    aracaju: {
      'a-pe': { kmh: 4.7, fatorRota: 1.25 },
      'carro-app': { kmh: 27, fatorRota: 1.35 },
      'transporte-publico': { kmh: 16, fatorRota: 1.45 },
      'veiculo-alugado': { kmh: 26, fatorRota: 1.35 },
    },
    'sao-luis': {
      'a-pe': { kmh: 4.5, fatorRota: 1.35 },
      'carro-app': { kmh: 22, fatorRota: 1.45 },
      'transporte-publico': { kmh: 14, fatorRota: 1.55 },
      'veiculo-alugado': { kmh: 21, fatorRota: 1.45 },
    },
    // Vila sem carro de passeio: tudo a pe, na areia; 4x4 so no entorno.
    jericoacoara: {
      'a-pe': { kmh: 3.8, fatorRota: 1.25 },
      'carro-app': { kmh: 18, fatorRota: 1.6 },
      'transporte-publico': { kmh: 15, fatorRota: 1.7 },
      'veiculo-alugado': { kmh: 18, fatorRota: 1.6 },
    },
    // Ilha sem rua para carro: carrinho de mao leva a mala.
    'morro-de-sao-paulo': {
      'a-pe': { kmh: 3.6, fatorRota: 1.4 },
      'carro-app': { kmh: 10, fatorRota: 1.8 },
      'transporte-publico': { kmh: 10, fatorRota: 1.8 },
      'veiculo-alugado': { kmh: 10, fatorRota: 1.8 },
    },
    atins: {
      'a-pe': { kmh: 3.8, fatorRota: 1.3 },
      'carro-app': { kmh: 16, fatorRota: 1.7 },
      'transporte-publico': { kmh: 16, fatorRota: 1.7 },
      'veiculo-alugado': { kmh: 16, fatorRota: 1.7 },
    },
    trancoso: {
      'a-pe': { kmh: 4.3, fatorRota: 1.3 },
      'carro-app': { kmh: 24, fatorRota: 1.45 },
      'transporte-publico': { kmh: 16, fatorRota: 1.6 },
      'veiculo-alugado': { kmh: 24, fatorRota: 1.45 },
    },
    // Serra: estrada de terra entre os atrativos.
    lencois: {
      'a-pe': { kmh: 4.2, fatorRota: 1.35 },
      'carro-app': { kmh: 22, fatorRota: 1.6 },
      'transporte-publico': { kmh: 18, fatorRota: 1.7 },
      'veiculo-alugado': { kmh: 22, fatorRota: 1.6 },
    },
  },

  /**
   * Fernando de Noronha e UTC-2: uma hora a frente do resto do Nordeste.
   * Sem isto, o voo de volta para Recife aparece com uma hora a menos e o
   * alerta de "nao voar depois de mergulhar" erra a conta.
   */
  fusoPorCidade: {
    'fernando-de-noronha': -120,
  },
};
